# Generated by Django 5.0.7 on 2024-07-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=13)),
                ('Subject', models.CharField(max_length=450)),
                ('Message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact-Infos',
            },
        ),
    ]
